"use client";

import type { AccountRiskReport as Report } from './crawl-api';

type Props = {
  report?:Report;
  language:'zh'|'en';
  canAnalyze:boolean;
  pending:boolean;
  onAnalyze:()=>void;
};

export default function AccountRiskReport({report,language,canAnalyze,pending,onAnalyze}:Props) {
  const T = (zh:string,en:string) => language==='en' ? en : zh;
  const narrative=language==='en' ? report?.narrative_en : report?.narrative;
  const conclusion=language==='en' ? report?.conclusion_en : report?.conclusion;
  const paragraphs=narrative?.length ? narrative : conclusion?.split(/\n\s*\n/) || [];
  const needsEnglish=language==='en' && !!report && !paragraphs.length;
  return <section className="st-account-risk" aria-label={T('账号分析文字','Account analysis text')}>
    <div className="st-risk-toolbar">
      <button className="st-crawl-secondary" disabled={!canAnalyze || pending} onClick={onAnalyze}>
        {pending ? T('本地 LLM 生成中…','Generating locally…') : T('更新分析','Refresh analysis')}
      </button>
    </div>
    <div className="st-risk-prose" lang={language==='en' ? 'en' : 'zh-CN'}>
      {paragraphs.length ? paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>) :
        <p>{needsEnglish ? 'Refresh analysis to generate the English text for this older collection.' : T('采集完成后，这里显示账号类型、具体可见信息和有依据的防范措施。','After collection, account type, specific visible information and evidence-based safeguards appear here.')}</p>}
    </div>
    {report?.generation?.kind==='rules' && <p className="st-risk-method">
      {T('生成方式：本地证据规则与文字模板；未调用 VLM／LLM，也未识别图片或转写音频。','Generated by local evidence rules and text templates; no VLM/LLM, image recognition or audio transcription.')}
      {report.generation.fallback_reason && <> {T('模型分析未完成：','Model generation incomplete: ')}{report.generation.fallback_reason}</>}
    </p>}
    {report?.generation?.kind==='llm' && <p className="st-risk-method">
      {T('正文由本地 ','Prose generated locally by ')}{report.generation.model}
      {T(' 生成；账号类型与证据规则保留，未识别图片或转写音频。','; account-type and evidence rules retained. No image recognition or audio transcription.')}
      {report.generation.elapsed_seconds != null && <> · {report.generation.elapsed_seconds} s</>}
    </p>}
  </section>;
}
