"""Small display derivatives of unchanged originals and real model MP4s."""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT=Path('D:/project/facebook/talking-head-lab')
RECORD=Path(__file__).resolve().parent
OUT=ROOT/'docs/showcase/gallery'
def linux(path):
    return '/mnt/d/'+path.relative_to(Path('D:/')).as_posix()
def wsl(*args):
    return subprocess.check_output(['wsl','-d','Ubuntu-22.04','--',*args],text=True)
cases=[]
for number in [1,2,3]:
    image=ROOT/'docs/showcase/synthetic-input.png' if number==1 else OUT/f'portrait-{number:02d}.png'
    video=ROOT/'docs/showcase/sadtalker-original-demo.mp4' if number==1 else OUT/f'video-{number:02d}.mp4'
    thumb=OUT/f'portrait-{number:02d}-thumb.jpg'
    gif=OUT/f'video-{number:02d}.gif'
    if not thumb.exists():
        wsl('ffmpeg','-v','error','-nostdin','-n','-i',linux(image),'-vf','scale=240:-1','-frames:v','1','-q:v','3',linux(thumb))
    filters='fps=8,scale=240:-1:flags=lanczos,drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:text=AI-GENERATED / SYNTHETIC:fontsize=12:fontcolor=white:box=1:boxcolor=black@0.6:x=7:y=h-24,split[a][b];[a]palettegen=max_colors=64[p];[b][p]paletteuse'
    if not gif.exists():
        wsl('ffmpeg','-v','error','-nostdin','-n','-i',linux(video),'-filter_complex',filters,'-loop','0',linux(gif))
    probe=json.loads(wsl('ffprobe','-v','error','-show_streams','-show_format','-of','json',linux(video)))
    case={'case':number,'input':image.relative_to(ROOT).as_posix(),'video':video.relative_to(ROOT).as_posix(),
          'thumbnail':thumb.relative_to(ROOT).as_posix(),'gif':gif.relative_to(ROOT).as_posix(),
          'input_sha256':hashlib.sha256(image.read_bytes()).hexdigest(),'video_sha256':hashlib.sha256(video.read_bytes()).hexdigest(),
          'duration_seconds':float(probe['format']['duration']),'has_audio':any(s['codec_type']=='audio' for s in probe['streams']),
          'width':next(s['width'] for s in probe['streams'] if s['codec_type']=='video'),
          'height':next(s['height'] for s in probe['streams'] if s['codec_type']=='video')}
    if number==1:
        job=json.loads((ROOT/'docs/change-records/2026-10-09-original-image-video/video-job.json').read_text(encoding='utf-8'))
        case.update(job_id=job['id'],model=job['model'],elapsed_seconds=job['elapsed_seconds'],scene=job['result']['scene'])
    else:
        state=json.loads((RECORD/f'case-{number:02d}.json').read_text(encoding='utf-8'))
        job=state['actual_job']
        case.update(job_id=job['id'],model=job['model'],elapsed_seconds=job['elapsed_seconds'],scene=job['result']['scene'],
                    input_byte_match=state['original_image_byte_match'],no_background_artifacts=state['no_background_artifacts'])
    assert case['has_audio'] and case['scene']=='original'
    cases.append(case)
manifest={'cases':cases,'audio':'docs/showcase/generated-voice.wav','audio_seconds':4.68,
          'input_source':'fictional people generated by built-in imagegen; not video-model output',
          'presentation_derivatives':'JPEG thumbnails and labeled silent GIF previews only; original PNG/MP4 unmodified',
          'new_video_jobs':2,'new_detection_jobs':0}
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'cases':[(c['case'],c['job_id'],c['duration_seconds']) for c in cases],'done':True}))
